server:
  port: 8088
---
spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: reservations
          uri: http://localhost:8081
          predicates:
            - Path=/reservations/**
        - id: payment
          uri: http://localhost:8082
          predicates:
            - Path=/payments/**
        - id: seatmanagement
          uri: http://localhost:8083
          predicates:
            - Path=/seats/**
        - id: ticketmanagement
          uri: http://localhost:8084
          predicates:
            - Path=/tickets/**
        - id: mypage
          uri: http://localhost:8085
          predicates:
            - Path= /myPages/**
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true
---
spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: reservations
          uri: http://reservations:8080
          predicates:
            - Path=/reservations/**
        - id: payment
          uri: http://payment:8080
          predicates:
            - Path=/payments/**
        - id: seatmanagement
          uri: http://seatmanagement:8080
          predicates:
            - Path=/seats/**
        - id: ticketmanagement
          uri: http://ticketmanagement:8080
          predicates:
            - Path=/tickets/**
        - id: mypage
          uri: http://mypage:8080
          predicates:
            - Path= /myPages/**
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
