apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypage
  labels:
    app: mypage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mypage
  template:
    metadata:
      labels:
        app: mypage
    spec:
      containers:
        - name: command-handler
          image: username/mypage-command-handler:latest
          ports:
            - containerPort: 8085
        - name: policy-handler
          image: username/mypage-policy-handler:latest