apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketmanagement
  labels:
    app: ticketmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketmanagement
  template:
    metadata:
      labels:
        app: ticketmanagement
    spec:
      containers:
        - name: ticketmanagement
          image: username/ticketmanagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5